config.schedule-messages: true

spring:
  jpa:
    show-sql: true

  datasource:
    username: "test"
    password: "test"
    driver-class-name: "org.postgresql.Driver"

  activemq:
    user: "admin"
    password: "admin"
    packages.trust-all: true

mockserver.initializationJsonPath: "resources/integration/mock-server.json"

bp:
  service:
    operational-gateway:
      template-id: "305003729"
      business-banking-url: "https://bancaempresas.pichincha.com"
    payment-execution:
      bgl-account: ""

  api-gee:
    headers.device: "TradeInnovationInterface"

    credentials:
      app-id: "app-id"
      api-key: "api-key000000000"
      api-secret: "api-secret000000"

    services:
      business-banking.url: "${bp.api-gee.base-url}/business-banking/v1"
      payment-execution.url: "${bp.api-gee.base-url}/payment-execution/v1"
      operational-gateway.url: "${bp.api-gee.base-url}/operational-gateway/v2"
      corporate-loan:
        user: ""
        operation-token: ""
        url: "${bp.api-gee.base-url}/domain/corporate-loan/v1"

sftp:
  user: "user"
  private-key: "key"
  host: "localhost"
  port: "22"
  local-dir:
    full-output: "./tmp/full-output"
    summary: "./tmp/summary"
  remote-dir:
    full-output: "/ti/full-output"
    summary: "/ti/summary"

fcm:
  activemq:
    # Set in AbstractIntegrationTest
    host: "localhost"
    port: "61616"
    user: "admin"
    password: "admin"
    broker-url: ""
    packages.trust-all: true

  config:
    debtor-id: "1182146"
    short-name: "20100105862"

  api:
    # Todo: don't upload this info
    headers.user-id: "171721"

    services:
      single-electronic-payment:
        url: "${bp.api-gee.base-url}/fcmclient/services/openapi/electronic"

  route:
    payment-result.from: "activemqFcm:queue:TRADE_INNOVATION_NOT"
    sftp:
      from-full-output: "direct:sendFullOutputToFcmViaSftp"
      from-summary: "direct:sendSummaryToFcmViaSftp"

ti.route:
  fti:
    out:
      from: "direct:sendToFtiOutgoingQueue"
      to: "activemq:queue:${ti.queue.fti.pub.name}?replyTo=${ti.queue.fti.reply.jndi}"
    in-reply.from: "activemq:queue:${ti.queue.fti.reply.name}"
  ticc.in.from: "activemq:queue:${ti.queue.ticc.sub.name}"
  scheduler.in.from: "activemq:queue:${ti.queue.scheduler.sub.name}"
