image: maven:3.9.3-amazoncorretto-17-debian

pipelines:
  default:
    - step:
        name: Build
        caches:
          - maven
        script:
          - echo "Building invoices..."
          - mvn -U clean package -DskipTests=true

    - step:
        name: Test
        script:
          - echo "Running tests..."
          - mvn test
