image: gradle:8.3.0-jdk17

definitions:
  steps:
    - step: &build
        name: Build
        caches: [ gradle ]
        script:
          - echo "Building invoices..."
          - gradle build --no-daemon -x test

    - step: &unit-tests
        name: Unit tests
        caches: [ gradle ]
        script:
          - echo "Running unit tests..."
          - gradle test --no-daemon

    - step: &integration-tests
        name: Integration tests
        services: [ docker ]
        caches: [ gradle, docker ]
        script:
          - echo "Running integration tests..."
          - export TESTCONTAINERS_RYUK_DISABLED=true
          - gradle integrationTest --no-daemon

    - step: &scan-dependencies
        name: Scan dependencies
        caches: [ gradle ]
        script:
          # Install snyk cli
          - export SNYK_TOKEN=$SNYK_TOKEN
          - curl https://static.snyk.io/cli/latest/snyk-linux --output snyk && chmod +x ./snyk
          - gradle build --no-daemon -x test
          - ./snyk test --all-projects

  services:
    docker:
      memory: 2048

pipelines:
  branches:
    # Production Branch
    main:
      - step: *build
      - step: *unit-tests

    # Test branch
    test:
      - step: *build
      - parallel:
          steps:
            - step: *unit-tests
            - step: *integration-tests

    # Development Branches
    develop:
      - step: *build
      - parallel:
          steps:
            - step: *unit-tests
            - step: *integration-tests
      - step: *scan-dependencies
        # Approve
    feat/*:
      - step: *build
      - parallel:
          steps:
            - step: *unit-tests
            - step: *integration-tests
