image: gradle:8.3.0-jdk17

definitions:
  services:
    docker:
      memory: 2048

  steps:
    - step: &build
        name: Build
        caches: [ gradle ]
        script:
          - gradle build --no-daemon -x test

    - step: &unit-tests
        name: Unit tests
        caches: [ gradle ]
        script:
          - gradle test --no-daemon

    - step: &integration-tests
        name: Integration tests
        services: [ docker ]
        caches: [ gradle, docker ]
        script:
          - export TESTCONTAINERS_RYUK_DISABLED=true
          - gradle integrationTest --no-daemon

    - step: &scan-dependencies
        name: Scan dependencies
        caches: [ gradle ]
        script:
          - chmod +x ./assets/scripts/install-snyk.sh && ./assets/scripts/install-snyk.sh
          - ./snyk test --all-projects --severity-threshold=medium
    - step: &scan-code
        name: Scan code
        caches: [ gradle ]
        script:
          - chmod +x ./assets/scripts/install-snyk.sh && ./assets/scripts/install-snyk.sh
          - ./snyk code test --severity-threshold=high
    - step: &scan-image
        name: Scan image
        caches: [ gradle, docker ]
        services: [ docker ]
        script:
          - chmod +x ./assets/scripts/install-snyk.sh && ./assets/scripts/install-snyk.sh
          - DOCKER_BUILDKIT=1 docker build -t $IMAGE:latest .
          - ./snyk container test $IMAGE:latest --severity-threshold=medium

    - step: &dev-approval
        name: Developer approval
        trigger: manual
        script:
          - echo "Step approved by developer"

    - step: &deploy-dev
        name: Deploy to development
        caches: [ gradle, docker ]
        services: [ docker ]
        script:
          - echo $CR_PASS_DEV | docker login $CR_NAME_DEV -u $CR_USER_DEV --password-stdin
          - DOCKER_BUILDKIT=1 docker build -t $CR_NAME_DEV/$IMAGE:latest .
          - docker push $CR_NAME_DEV/$IMAGE:latest

    - step: &deploy-test
        name: Deploy to test
        caches: [ gradle, docker ]
        services: [ docker ]
        script:
          - echo $CR_PASS_TEST | docker login $CR_NAME_TEST -u $CR_USER_TEST --password-stdin
          - DOCKER_BUILDKIT=1 docker build -t $CR_NAME_TEST/$IMAGE:latest .
          - docker push $CR_NAME_TEST/$IMAGE:latest


pipelines:
  branches:
    # Production Branch
    main:
      - step: *build
      - step: *unit-tests

    # Staging (Test) branch
    develop:
      - step: *build
      - parallel:
          steps:
            - step: *unit-tests
            - step: *integration-tests
      - parallel: # Snyk scans
          steps:
            - step: *scan-dependencies
            - step: *scan-code
            - step: *scan-image
      - step: *deploy-test

    # Development Branches
    feat/*:
      - step: *build
      - parallel:
          steps:
            - step: *unit-tests
            - step: *integration-tests
      - parallel: # Snyk scans
          steps:
            - step: *scan-dependencies
            - step: *scan-code
            - step: *scan-image
      - step: *dev-approval
      - step: *deploy-dev
