image: maven:3.9.3-amazoncorretto-17-debian

pipelines:
  default:
    - step:
        name: Build
        caches:
          - maven
        script:
          - echo "Building invoices..."
          - mvn -U clean package -DskipTests=true

    - step:
        name: Test
        script:
          - echo "Running tests..."
          - mvn test

    - step:
        name: Deploy
        script:
          - echo "Installing Azure CLI..."
          - curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash
          - echo "Deploying application to Azure functions..."
          - echo $AZURE_FUNCTIONS_PUBLISH_CREDENTIALS > ./azure-functions-credentials.publishsettings
          - az login --service-principal -u $AZURE_CLIENT_ID -p $AZURE_CLIENT_SECRET --tenant $AZURE_TENANT_ID
          - mvn azure-functions:deploy
