image: gradle:8.3.0-jdk17

pipelines:
  default:
    - step:
        name: Build
        caches:
          - gradle
        script:
          - echo "Building invoices..."
          - gradle build -x test

    - step:
        name: Test
        script:
          - echo "Running tests..."
          - gradle test
