image: gradle:8.3.0-jdk17

definitions:
  steps:
    - step: &build
        name: Build app
        caches: [ gradle ]
        script:
          - echo "Building invoices..."
          - gradle build -x test

    - step: &test
        name: Run unit tests
        caches: [ gradle ]
        script:
          - echo "Running tests..."
          - gradle test

    - step: &deploy-dev
        name: Deploy
        caches: [ gradle ]
        script:
          - echo "Deploying to development"
          - pipe: atlassian/azure-web-apps-containers-deploy:1.2.0
            variables:
              AZURE_APP_ID: $AZ_APP_ID
              AZURE_PASSWORD: $AZ_PASSWORD
              AZURE_TENANT_ID: $AZ_TENANT
              AZURE_SUBSCRIPTION: $AZ_SUBSCRIPTION_ID_TI_DEV
              AZURE_RESOURCE_GROUP: 'rg-pch-tidev-appserv-01' # Important: this might change
              AZURE_APP_NAME: 'astipch-invoices-dev'
              DOCKER_CUSTOM_IMAGE_NAME: 'ti-invoices'
              DOCKER_REGISTRY_SERVER_URL: 'crpchtidev01.azurecr.io'
              DOCKER_REGISTRY_SERVER_USER: 'crpchtidev01'
              DOCKER_REGISTRY_SERVER_PASSWORD: $ACR_PASSWORD

pipelines:
  branches:
    main:
      - step: *build
      - step: *test

    qa:
      - step: *build
      - step: *test

    develop:
      - step: *build
      - step: *test
      - step: *deploy-dev
