image: maven:3.9.3-amazoncorretto-17-debian

pipelines:
  default:
    - step:
        name: Build
        caches:
          - gradle
        script:
          - echo "Building invoices..."
          - ./gradlew clean build -x test

    - step:
        name: Test
        script:
          - echo "Running tests..."
          - mvn test
