spring:
  profiles:
    active: ${APPLICATION_ENV:dev}
  jpa:
    open-in-view: true
  output:
    ansi:
      enabled: ALWAYS

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    path: '/swagger.html'