spring:
  datasource:
    host: "<...>"
    port: "<...>"
    username: "<...>"
    password: "<...>"
    url: "jdbc:sqlserver://${spring.datasource.host}:${spring.datasource.port};database=TIZONE1;encrypt=true;trustServerCertificate=true;"
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver

  activemq:
    host: "<...>"
    port: "<...>"
    user: "<...>"
    password: "<...>"
    broker-url: "tcp://${spring.activemq.host}:${spring.activemq.port}"
    packages:
      trust-all: true

invoice:
  route:
    create:
      queue-pub:
        name: "BP.DIGIBANK.TO.FTI"
      queue-sub:
        name: "BP.DIGIBANK.TO.FTI.REPLY"
        jndi: "queue/digibankInIncomingReply"
      from: "direct:createInvoiceInTI"
      to-pub: "activemq:queue:${invoice.route.create.queue-pub.name}?replyTo=${invoice.route.create.queue-sub.jndi}"
      to-sub: "activemq:queue:${invoice.route.create.queue-sub.name}"

program:
  route:
    create:
      from: "direct:createProgramInTI"
      to: "mock:programQueue"