spring:
  datasource:
    # Local DB
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/zone
    username: <db-user>
    password: <db-pass>

  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB

  activemq:
    user: <mq-user>
    password: <mq-password>
    broker-url: tcp://localhost:<mq-port>

  output:
    ansi:
      enabled: ALWAYS

  jpa:
    open-in-view: true

springdoc:
  api-docs:
    enabled: true

  swagger-ui:
    path: '/swagger.html'
