server.port: ${APPLICATION_PORT:8080}

spring:
  profiles.active: ${APPLICATION_ENV:prod}

  jpa:
    open-in-view: true
    database-platform: "org.hibernate.dialect.SQLServerDialect"
    properties.hibernate:
      dialect: "org.hibernate.dialect.SQLServerDialect"

ti:
  queue:
    pub:
      name: "BP.DIGIBANK.TO.FTI"
    reply:
      name: "BP.DIGIBANK.TO.FTI.REPLY"
      jndi: "queue/digibankInIncomingReply"

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    path: '/swagger.html'
