spring:
  datasource:
    host: "<...>"
    port: "<...>"
    username: "<...>"
    password: "<...>"
    url: "jdbc:sqlserver://${spring.datasource.host}:${spring.datasource.port};database=TIZONE1;encrypt=true;trustServerCertificate=true;"
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver

  activemq:
    host: "<...>"
    port: "<...>"
    user: "<...>"
    password: "<...>"
    broker-url: "tcp://${spring.activemq.host}:${spring.activemq.port}"
    packages:
      trust-all: true

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLServerDialect

invoice:
  route:
    create:
      queue: "DEV.TEST"
      from: "direct:createInvoiceInTI"
      to: "activemq:queue:${invoice.route.create.queue}"

program:
  route:
    create:
      from: "direct:createProgramInTI"
      to: "mock:programQueue"
