server.port: ${APPLICATION_PORT:8080}

logging.level.org.springframework.web.filter.RequestTraceLogLoggingFilter: DEBUG

spring:
  profiles.active: ${APPLICATION_ENV:prod}

  jpa:
    open-in-view: true
    database-platform: "org.hibernate.dialect.SQLServerDialect"
    properties.hibernate:
      dialect: "org.hibernate.dialect.SQLServerDialect"

ti:
  queue:
    pub:
      name: "BP.DIGIBANK.TO.FTI"
    reply:
      name: "BP.DIGIBANK.TO.FTI.REPLY"
      jndi: "queue/digibankInIncomingReply"

bp.api-gee.url:
  dev: "https://api-dev.pichincha.com"
  test: "https://api-test.pichincha.com"
  prod: ""

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    path: '/swagger.html'
