server.port: ${APPLICATION_PORT:8080}

logging.level.org.springframework.web.filter.RequestTraceLogLoggingFilter: DEBUG

spring:
  profiles.active: ${APPLICATION_ENV:local}
  jackson.time-zone: "America/Guayaquil"
  jpa.open-in-view: true

ti.queue:
  fti:
    pub.name: "BP.DIGIBANK.TO.FTI"
    sub.name: "BP.FTI.TO.DIGIBANK"
    reply:
      name: "BP.DIGIBANK.TO.FTI.REPLY"
      jndi: "queue/digibankInIncomingReply"
  ticc.sub.name: "BP.TICC.TO.DIGIBANK"
  # Custom component
  scheduler.sub.name: "BP.SCHEDULER.TO.DIGIBANK"

bp.api-gee.url:
  dev: "https://api-dev.pichincha.com"
  test: "https://api-test.pichincha.com"
  prod: "https://api.pichincha.com"

springdoc:
  api-docs.enabled: true
  swagger-ui.path: '/swagger.html'
