configuration:
  zone-id: "America/Guayaquil"

server.port: ${APPLICATION_PORT:8080}

logging.level.org.springframework.web.filter.RequestTraceLogLoggingFilter: DEBUG

spring:
  profiles.active: ${APPLICATION_ENV:local}
  jackson.time-zone: ${configuration.zone-id}
  jpa.open-in-view: true

ti.queue:
  fti:
    pub.name: "BP.DIGIBANK.TO.FTI"
    sub.name: "BP.FTI.TO.DIGIBANK"
    reply:
      name: "BP.DIGIBANK.TO.FTI.REPLY"
      jndi: "queue/digibankInIncomingReply"
  ticc.sub.name: "BP.TICC.TO.DIGIBANK"
  # Custom component
  scheduler.sub.name: "BP.TI.TO.SCHEDULER"

bp.api-gee.url:
  dev: "https://api-dev.pichincha.com"
  test: "https://api-test.pichincha.com"
  prod: "https://api.pichincha.com"

fcm:
  queue:
    notification.sub.name: "TRADE_INNOVATION_NOT"

  api.url:
    dev: "http://172.31.96.5:8080"
    test: "http://172.31.112.4:8080"

springdoc:
  api-docs.enabled: true
  swagger-ui.path: '/swagger.html'
