spring:
  datasource:
    # Local DB
     driver-class-name: com.mysql.cj.jdbc.Driver
     url: jdbc:mysql://localhost:3306/zone
     username: root
     password: Master123

  servlet:
    multipart:
      # TODO: confirmar esto con Frank (vulnerabilidad)
      max-file-size: 5MB
      max-request-size: 5MB

  activemq:
    user: admin
    password: admin
    broker-url: tcp://localhost:61616

    # Testing DB
  #    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
#    url: jdbc:sqlserver://172.31.48.4:1453;database=TIZONE1
#    username: development
#    password: BPCH_2023&

  output:
    ansi:
      enabled: ALWAYS

  jpa:
    open-in-view: true

springdoc:
  api-docs:
    enabled: true

  swagger-ui:
    path: '/swagger.html'
